# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='names',
        ),
    ]
